### ISSUE TITLE
Infernus IV Lasgun (Infantry)

### ISSUE THREAD

**Issue by lardeg** [nleclerc/darktide-blessingtracker#2]
Lasgun (Infantry) can't pick  Infernus IV
![image](https://user-images.githubusercontent.com/37995736/224525509-b57f011a-3db9-4b5b-828f-bdaff71a165a.png)

**Comment by nleclerc** [comment]
I'm sorry but i don't really understand what your issue is.
More importantly i'm not affiliated with fatshark or anything so if you found a bug in the game you need to post it on the fatshark forums : https://forums.fatsharkgames.com/c/darktide/bugs/94

**Comment by lardeg** [comment]
I can't pick Infernus IV on Lasgun (Infantry) in blessing tracker. But i have it in game.
![image](https://user-images.githubusercontent.com/37995736/225346402-ad3ed7ce-cbfc-4755-bf20-e292845c0aac.png)

**Comment by nleclerc** [comment]
Ok sorry.
I'll look into it cause i think infernus is lvl 3 only on some other weapon.
Thanks for the report.

**Comment by nleclerc** [comment]
ok so i've allowed setting infernus at all levels for now.
